### ISSUE TITLE
About net.W Issue.

### ISSUE THREAD

**Issue by Fyzjym** [aimagelab/VATr#10]
hi，thanks your great wok!
I noticed code：
model.py @397 lines
'''
        self.netW = WDiscriminator(
            resolution=self.args.resolution, n_classes=self.args.vocab_size, output_dim=self.args.num_writers
        ).to(self.args.device)
'''
Why n_classes is self.args.vocab_size, 
does net.W classify the author wid? 
net.W is still responsible for classifying characters in the vocabulary table?

**Comment by vittoriopippi** [comment]
Hi @Fyzjym!
The [`WDiscriminator`](https://github.com/aimagelab/VATr/blob/f2fd466511f041ba2f87de54fcfad30797954bb4/models/BigGAN_networks.py#L623) class is responsible to the Writer Identification. The fact that class `WDiscriminator` takes as input the `n_classes` is a refuse of old code from the [Handwriting-Transformers GitHub repo](https://github.com/ankanbhunia/Handwriting-Transformers).

The `n_classes` parameter is stored into the class variables ([Line 646](https://github.com/aimagelab/VATr/blob/f2fd466511f041ba2f87de54fcfad30797954bb4/models/BigGAN_networks.py#L646)) and it is used to create the variable `embed` ([Line 710](https://github.com/aimagelab/VATr/blob/f2fd466511f041ba2f87de54fcfad30797954bb4/models/BigGAN_networks.py#L710C27-L710C42))  that is never used into the class.

**Comment by Fyzjym** [comment]
I completely agree with your point of view. Thank you for your prompt and effective responses! 
:D
