### ISSUE TITLE
IV-S，IV-U，OOV-S，OOV-U的设置

### ISSUE THREAD

**Issue by yuyukuy534** [aimagelab/VATr#13]
Hello author, I take the liberty of bothering you, thank you for your excellent paper. Recently, I read your paper and I have a question I would like to ask you about the In-Vocabulary words and seen style (IV-S), In-Vocabulary words and unseen style (IV-U), Out-of-vocabulary words and seen styles (OOV-S) mentioned in your paper. How do you set Out-of-vocabulary words and unseen styles (OOV-U)? Looking forward to your guidance and response. Thank you!

**Comment by vittoriopippi** [comment]
Hello @yuyukuy534, you can find the OOV words here: https://github.com/aimagelab/VATr/blob/main/corpora_english/oov_words.txt

The styles are those from the IAM test set: https://github.com/aimagelab/VATr/blob/main/Groundtruth/gan.iam.test.gt.filter27

**Comment by yuyukuy534** [comment]
@vittoriopippi  Hello, I have been looking up information to learn how to use OOV_word.text to calculate the FID value of OOV, but I still don't understand it. I hope I can get your guidance and help
