### ISSUE TITLE
weights for complete network

### ISSUE THREAD

**Issue by SidraHanif180** [aimagelab/VATr#16]
Hi,

Thanks for sharing your work on VATr. 
I want to ask you if you can share the pre-trained weights for the complete network.

**Comment by yuyukuy534** [comment]
> Hi,
> 
> Thanks for sharing your work on VATr. I want to ask you if you can share the pre-trained weights for the complete network.

Hello, I'm sorry to bother you. Why do you need more than 700 seconds for each round of training after python train. py? Is this normal?

**Comment by vittoriopippi** [comment]
hello @SidraHanif180, you can find the checkpoints in the releases. This is the URL: https://github.com/aimagelab/VATr/releases/tag/checkpoints
