### ISSUE TITLE
execute  python generate_fakes.py --checkpoint files/vatr.pth have wrong

### ISSUE THREAD

**Issue by yuyukuy534** [aimagelab/VATr#20]
Hello, I  get this error  "assert len(old_model) == len(checkpoint) "  when I execute python generate_fakes.py --checkpoint files/vatr.pth code, what is the reason for this?

**Comment by vittoriopippi** [comment]
I've just cloned the repo, and the command `python generate_fakes.py --checkpoint files/vatr.pth` doesn't give me any error. Please double-check your code before opening these issues.

**Comment by yuyukuy534** [comment]
Hello, can you send me your generate_fakes. py file, I downloaded it from github and run it all the time with AssertionError

**Comment by vittoriopippi** [comment]
The downloaded file I've used is what you can find on GitHub. Which checkpoint are you using for the generation?

**Comment by yuyukuy534** [comment]
I downloaded vatr.pth and command python generate_fakes. py--checkpoint files/vatr.pth, reporting an error of AssertionError
<img width="703" alt="68a680f94928ff96ea90ab9530d318b" src="https://github.com/aimagelab/VATr/assets/41134979/d5f5cd5c-beed-4916-ae7a-334e8e527921">

**Comment by yuyukuy534** [comment]
I print the  len (checkpoint) and len (old_model) values, which are really not equal. One is equal to 941 and the other is equal to 997, so an error is reported as AssertionError 
<img width="629" alt="61bda3388c4f6a182357be487490940" src="https://github.com/aimagelab/VATr/assets/41134979/aae03da6-3fc1-4ebb-b1c7-50833c883587">

**Comment by vittoriopippi** [comment]
There is probably something wrong with your checkpoint since the `vatr.pth` checkpoint I've shared works completely fine. You are probably using a checkpoint trained by yourself. In that case, you should change the arguments of `generate_fakes.py` to match the same ones you've used during training.

If you have downloaded it, please ensure the checkpoint is downloaded correctly. Check if the checksum is the same as below:
```bash
(vatr) user@node:~/VATr$ md5sum files/vatr.pth 
d1386fd46314dd281d9046cd4d6e3852  files/vatr.pth
```
If not please download it again ([link](https://github.com/aimagelab/VATr/releases/download/checkpoints/vatr.pth))

**Comment by yuyukuy534** [comment]
@vittoriopippi  Thank you very much for your timely reply. After I downloaded vatr.pth correctly, I executed the command to report an error of 'KeyError:' img_id '. What caused this? 
<img width="944" alt="cebdee8a7df8b7d80ea2c3af81d9844" src="https://github.com/aimagelab/VATr/assets/41134979/b12d9af2-4525-4c41-8ddc-27ee4c85e613">

**Comment by vittoriopippi** [comment]
Please follow the installation guide in the readme because you are using the wrong files. The `IAM-32.pickle` I've used differs from the one shared by HWT. My pickle file also includes a unique ID for each image.

https://github.com/aimagelab/VATr#installation

**Comment by yuyukuy534** [comment]
@vittoriopippi Hello, I have been looking up information to learn how to use OOV_word.text to calculate the FID value of OOV, but I still don't understand it. I hope I can get your guidance and help
