### ISSUE TITLE
i trained and used the model.pth after 100 epochs but i see the image created from generator.py is with only disturbance

### ISSUE THREAD

**Issue by NavyaYadlapalli99** [aimagelab/VATr#4]
Am i doing something wrong . Please help me with this.

**Comment by vittoriopippi** [comment]
Hi @NavyaYadlapalli99, 100 epochs are not enough to get some results. Please refer to issue #3, where there are the expected intermediate results of the first epochs

**Comment by NavyaYadlapalli99** [comment]
Hi I have now trained the model for 1690 epochs but still see the results are not to the expected range i generated a word with word ''Aaronic" and it looks like this .


![Aaronic](https://github.com/aimagelab/VATr/assets/64828589/a5e08680-50e7-46b0-97ea-73422fcfbd51)

**Comment by NavyaYadlapalli99** [comment]
Can you please help why my A is still like this and few other words i observed the similar behavior.

**Comment by vittoriopippi** [comment]
Dear @NavyaYadlapalli99 the VATr model is trained for more than 7000 epochs, the model that you show us is on a good path, keep training it if you want a better generation

**Comment by NavyaYadlapalli99** [comment]
one last doubt is that after getting the model trained for enough epochs its only possible that we can generate data only for three different styles provided ?? or can we add beforehand some more styles for it to perform?

**Comment by NavyaYadlapalli99** [comment]
Please can u help with my last comment ?

**Comment by lerndeep** [comment]
@vittoriopippi @NavyaYadlapalli99 @baraldilorenzo Could you please let me know the data preparation code for .pickle format?

**Comment by silviaCascianelli** [comment]
@NavyaYadlapalli99 Once the model is trained, it can be used to generate text in an unlimited number of unseen styles (please, refer to the [paper](https://arxiv.org/pdf/2303.15269.pdf) for further details). Probably, you will obtain the best results on styles from the IAM test set, but there is no technical constraint on the style the trained model can be asked to imitate.

**Comment by silviaCascianelli** [comment]
@lerndeep Your comment seems out-of-context for this issue. I suggest you open a new, dedicated one.

**Comment by NavyaYadlapalli99** [comment]
@silviaCascianelli @vittoriopippi I have trained the model but if i want to increase the text size in the images generated is it possible?

**Comment by silviaCascianelli** [comment]
Do you mean generating longer words? Yes, It Is possibile (and you can even generate entire Lines of multiple words)

**Comment by NavyaYadlapalli99** [comment]
No not length size of the text that is generated means writing bigger letters

**Comment by vittoriopippi** [comment]
You can definitely generate bigger images by changing the architecture. In particular you should focus on the CNN Decoder at the end of the network. 

In any case we never tried this option, therefore we don't know if the network could train properly.

**Comment by NavyaYadlapalli99** [comment]
Thanks for the quick reply :)

**Comment by NavyaYadlapalli99** [comment]
And also i added few style folders and tried generating images with style apart from what you provided

**Comment by Sdfabio** [comment]
And what were your results ? mine was not concluent, the model still used styles from trained/test dataset
