### ISSUE TITLE
Dear author how to get FID、GER、GS indexs

### ISSUE THREAD

**Issue by zfcbest** [aimagelab/VATr#6]

**Comment by silviaCascianelli** [comment]
As for the FID and GS, we follow the same procedure (and use the same code) as the one proposed in the [GANwriting paper](https://github.com/omni-us/research-GANwriting/tree/master), which is commonly adopted in the HTG community.
For the CER, you can use any library that computes it (eg: [xer](https://github.com/jpuigcerver/xer), [editdistance](https://pypi.org/project/editdistance/) - the one we used -, [fastwer](https://github.com/kahne/fastwer)) on the output of a an HTR model trained on IAM.

**Comment by zfcbest** [comment]
> 至于FID和GS，我们遵循与[GANwriting](https://github.com/omni-us/research-GANwriting/tree/master)论文中提出的相同的程序（并使用相同的代码），该论文在HTG社区中普遍采用。对于 CER，您可以使用任何在 IAM 上训练的 HTR 模型的输出上计算它的库（例如：[xer](https://github.com/jpuigcerver/xer)、[editdistance](https://pypi.org/project/editdistance/) - 我们使用的那个 -，[fastwer](https://github.com/kahne/fastwer)）。

Thank you dear author, good luck and happiness forever

**Comment by silviaCascianelli** [comment]
Aaaaw! Thank you! The best of luck with your research, we hope our repo helps!
